# Default values for bWAPP.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

name: bwapp

labels:
  app: bwapp

selectorLabels:
  app: bwapp

image:
  repository: nikhilrajesh/bwapp
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []

podAnnotations: {}

service:
  type: ClusterIP
  port: 4000

resources: {}
